### ISSUE TITLE
Hormann Homee 

### ISSUE THREAD

**Issue by Bodie2005** [stfnhmplr/homebridge-homee#21]
Hi there.
    I have bought Hormann Homee BiSecur Cube and unfortunately I didn't see any devices (gates, etc.). On iOS app I see, that homebridge is connected, in HB that Homee is connected too. Is it because I am doing anything wrong, or Hormann Cube is unsupported.
Brain Cube: 2.33.1
App: 2.33
Thank you for any idea.

**Comment by stfnhmplr** [comment]
Due to low demand, the feature has not yet been developed further. There is a beta version available for testing purposes with the support for garage doors. You can test the beta version (`npm install -g homebridge-homee@beta`) and report if it works. However, I can't promise to finish developing the feature for you alone.
